const products = [
    {
        name: "ALL IN ONE",
        contents: "Combination of amino acids and vitamins",
        dosage: "1ml/ ltr water",
        weight: "1 Ltr",
        mrp: "₹1150/-",
        quantity: "500 ml / 1000 ml",
        image1: "https://drive.google.com/file/d/1ORTsOfo_3z6lAGjC4bSG0aUig0a35GWZ/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1HY1Dn0mrIirwVmvwOC4ACGDNaA5Bacmv/view?usp=sharing"
    },
    {
        name: "ALL IN ONE (Metallic)",
        contents: "Combination of L-amino acids and vitamins",
        dosage: "1ml/ ltr water",
        weight: "1 Ltr",
        mrp: "₹1210/-",
        quantity: "500 ml / 1000 ml",
        image1: "https://drive.google.com/file/d/1grJaMRdt-nkPlb6gO1HGrShwXw2PPDqX/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1jfDcgfZDtYNNsV2C7fdZz_jrqwa2sor_/view?usp=sharing",
        image3: "https://drive.google.com/file/d/1wXbr4y0pMYN_CGTgjtIOBeXazujYyWhK/view?usp=sharing"
    },
    {
        name: "COMBI MICRO (Chelated liquid micro nutrient)",
        contents: "Combination of micronutrients- Zinc 5%, Ferrous 2.5%, Boron 0.5%, Molybdenum 0.1%",
        dosage: "1ml/ ltr water",
        weight: "1 Ltr",
        mrp: "₹899/-",
        quantity: "500 ml / 1 Ltr / 5 Ltr",
        image1: "https://drive.google.com/file/d/1CINuwvgxN_NpSNw36zxEUnsU5QXTqjlv/view?usp=sharing",
        image2: "https://drive.google.com/file/d/10O9mZ6FdEBpTOmP_N4lMdi6ewK9TGfHx/view?usp=sharing",
        image3: "https://drive.google.com/file/d/14is3SJjjx9uKjy6g0Q-gJTEmfjRh99jj/view?usp=sharing"
    },
    {
        name: "BLOOM 555",
        contents: "Combination of carbohydrates 0.06% and proteins 50%",
        dosage: "50ml - 250ml per acre or 0.5ml - 1ml/lit water",
        weight: "250 ml",
        mrp: "₹850/-",
        quantity: "100 ml / 500 ml",
        image1: "https://drive.google.com/file/d/1G-aU1oJwM3f-auh4gJaHB_InEc_gYt4L/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1zIfCE_r2ikX9Muc5ifsjfjM06X5u-d5k/view?usp=sharing",
    },
    {
        name: "BIOSTEEM BIOSTIMULANTS",
        contents: "Folic acid 0.1%, carboxylic acid 6% and combination of phytohormones",
        dosage: "0.5ml - 1ml / ltr water",
        weight: "500 ml",
        mrp: "₹1250/-",
        quantity: "100 ml / 250 ml",
        image1: "https://drive.google.com/file/d/1n2JSROzuo1xILVsz_jpiSeELuLVNbINR/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1mQXZVKLXlqGQJKQKVS0qp7aP12lNBOEB/view?usp=sharing",
    },
    {
        name: " MEGAHUMUS",
        contents: "Humic acid 36%, and folic acid 5%",
        dosage: "3-4ml / ltr water",
        weight: "500 ml",
        mrp: "₹360/-",
        quantity: "500 ml / 1 Ltr / 5 Ltr ",
        image1: "https://drive.google.com/file/d/1jSeIoBKawUzU-Vj1NR19o9FdhWGxQRFW/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1K1YwSep6ymgJLjnlCsy_bLaGL0KJYc2y/view?usp=sharing",
    },
    {
        name: " ROOTER",
        contents: "Super humate 98% & fulvic acid 1.5%",
        dosage: "1gm/ ltr water",
        weight: "500 gm",
        mrp: "₹1300/-",
        quantity: "100 gm / 250 gm / 500 gm ",
        image1: "https://drive.google.com/file/d/1FR8XTqV7-miNaV-tUPQyYiAhpq6sD_Ao/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1yg2B7Wk1XEkHNn1t6Juy7Z2PfOB-9sNt/view?usp=sharing",
    },
    {
        name: " SAMRUDDHI",
        contents: "Boron 20 % (Disodium Octaborate Tetrahydrate)",
        dosage: "1gm / ltr water",
        weight: "500 gm",
        mrp: "₹425/-",
        quantity: "100 gm / 250 gm / 500 gm ",
        image1: "https://drive.google.com/file/d/1ee0n-1z3VHhqMATXdQ1jmJ89IKqU_WJC/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1MB7f2jiGG9-8HmdM_XyzF5lnNSk_bae6/view?usp=sharing",
    },
    {
        name: "PICKUP",
        contents: "Super humate 98% & fulvic acid 0.5%",
        dosage: "1gm / ltr water",
        weight: "500 gm",
        mrp: "₹1430/-",
        quantity: "100 gm / 250 gm / 500 gm ",
        image1: "https://drive.google.com/file/d/1VP3DPS-GYT2E6NbDJmAz-sbKArsMge1c/view?usp=sharing",
        image2: "https://drive.google.com/file/d/17Bwuu5FgeFmJpQDmig6Lntl1RjweWWrA/view?usp=sharing",
    },
    {
        name: "LOTUS",
        contents: "Amino acid, combination of phytohormones, bronopol, atonik, humic acid, silicon and brassinolid",
        dosage: " 0.5-1gm / Ltr water",
        weight: "500 gm",
        mrp: "₹1350/-",
        quantity: "100 gm / 250 gm / 500 gm ",
        image1: "https://drive.google.com/file/d/1VP3DPS-GYT2E6NbDJmAz-sbKArsMge1c/view?usp=sharing",
        image2: "https://drive.google.com/file/d/17Bwuu5FgeFmJpQDmig6Lntl1RjweWWrA/view?usp=sharing",
    },
    {
        name: "SAMRUDDHI",
        contents: "Chelated zinc EDTA 12%",
        dosage: "Foliar application: 1gm/Ltr water Soil application: 500gm-1kg/acre",
        weight: "500 gm",
        mrp: "₹610/-",
        quantity: "100 gm / 250 gm / 500 gm ",
        image1: "https://drive.google.com/file/d/1TuN3IogLRyAkH2hPCGKl9Xo6phi6yEFs/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1R_APFauoq-4al4jzVdUso4lL8I23S7Ol/view?usp=sharing",
    },
    {
        name: "SAMRUDDHI",
        contents: "Chelated mix combination of micronutrients- EDTA Zn 3%, Cu 1%, Fe 2.5%, Mn 1%, B 0.5%, Mo 0.1%",
        dosage: "Foliar application: 1gm/Ltr water Soil application: 250gm-500gm/acre.",
        weight: "500 gm",
        mrp: "₹590/-",
        quantity: "100 gm / 250 gm / 500 gm ",
        image1: "https://drive.google.com/file/d/1RPEdGrsJWTsL56Fzmd6wpS0S34eFK30-/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1fM2nLL6jmlrf5gKCRm2DKyOy8qurNz8q/view?usp=sharing",
    },
    {
        name: "SAMRUDDHI (Mix micronutrients)",
        contents: "Zn 5%, Fe 2%, Cu 0.5%, Mn 1%, & B 1%",
        dosage: "10 kg/acre",
        weight: "10 kg",
        mrp: "₹895/-",
        quantity: "100 gm / 250 gm / 500 gm ",
        image1: "https://drive.google.com/file/d/1mMKiqZsjcjE1ngF7fBiiL85FHAQqTq9o/view?usp=sharing",
    },
    {
        name: "MEGAZYME (Granuales)",
        contents: "Humic acid, Seaweed extract, amino acid, protein and phytohormones",
        dosage: "Soil application- 25kg/hectare",
        weight: "25 kg",
        mrp: "₹2050/-",
        quantity: "25 kg",
        image1: "https://drive.google.com/file/d/1T1DJXhaeZyyehNHRNpAG4ZHVUqQ0B9Rf/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1Igt17wio9z2uPCnbT-G4RcqNDGnigR7V/view?usp=sharing",
    },
    {
        name: "SAMRUDHHI (Combi kit)",
        contents: "Zinc 7.5kg, Magnesium 15kg, Ferrous 5kg, Manganese 1.5kg, Boron 1kg",
        dosage: "Soil application- 30kg/ hectare",
        weight: "30 kg",
        mrp: "₹2150/-",
        quantity: "30 kg",
        image1: "https://drive.google.com/file/d/1pLdVEKAMekyFhtmmNY3Jx82abIrOWhU9/view?usp=sharing",
        image2: "https://drive.google.com/file/d/1XCHYUroMxtD_Y1AGnstz4QtoNO2pd3HK/view?usp=sharing",
    },
]